### ISSUE TITLE
Agrega la redirección de url luego del registro de un usuario.

### ISSUE THREAD

**Issue by ework** [ework/IS-2016-Team-2#29]
Igual que en el login, luego de registrar un nuevo usuario nos debe de redireccionar a la página de inicio si el registro fue exitoso. 

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by SebastianWilde** [comment]
a la página de inicio o a la de usuario ya con los datos cargados?? @ework

**Comment by ework** [comment]
a la página de inicio :+1:

**Comment by SebastianWilde** [comment]
Issue terminado entonces
